#!/bin/bash

cd /app

URL=`node ./scripts/getMultipaperVersionUrl.js $VERSION | jq -r '.app'`

curl $URL > /data/multipaper.jar

i=1

while [ "$i" -le "$INSTANCES" ]; do
    
    echo "Starting instance $i"
    dir=/data/server_$i
    if [ ! -d $dir ]
    then
        echo "No instance found, generating..."
        mkdir $dir
    fi
    cd $dir

    echo "eula=true" > eula.txt
    echo $OPS > ops.txt

    if [ ! -f ./multipaper.yml ]
    then
        curl https://server.properties > server.properties
        cp /app/scripts/spigot.yml spigot.yml
        cp /data/multipaper.jar ./multipaper.jar
        java -jar multipaper.jar > ../server_$i.log &
        PID=$!
        while [ ! -f ./multipaper.yml ]; do 
            sleep 1;
        done
        kill $PID
        echo 'java -jar multipaper.jar > ../server_$i.log &' > start.sh
        chmod +x start.sh
        # yq -i ".multipaperMasterAddress = \"$MASTER\"" ./multipaper.yml
        /app/scripts/yq -i ".[\"master-connection\"][\"master-address\"] = \"$MASTER\"" ./multipaper.yml
        sed -i "s/25565/$((25577+$i))/" ./server.properties

        # echo $PROXY;

        # if [ -z "$PROXY" ]
        # then
        #     echo "PROXY not set, using default value"
        # else
        #     if [ "$PROXY" = "VELOCITY" ]
        #     then
        #         mkdir -p plugins/
        #         PLUGIN_URL=`curl https://api.github.com/repos/bhopahk/VelocityLoadBalancer/releases/latest | jq -r '.assets[].browser_download_url'`
        #         curl $PLUGIN_URL > plugins/VelocityLoadBalancer.jar
        #     fi
        # fi


        screen -d -m java -jar multipaper.jar >> ../server_$i.log
    else
        screen -d -m java -jar multipaper.jar >> ../server_$i.log
    fi
    i=$(($i + 1))
done

tail -f ../*.log